### ISSUE TITLE
upgrade the reference subnet contracts deployed from the registry

### ISSUE THREAD

**Issue by snissn** [consensus-shipyard/ipc-solidity-actors#287]
This code makes the registry contract upgradable, but unless I am missing something, we are not offering a way to upgrade the reference subnet contracts deployed from the registry, right? 

In order to upgrade the reference subnet contract to deploy through the registry would be as simple as exposing a method that allows changing the facet addresses that we are pointing to here: https://github.com/consensus-shipyard/ipc-solidity-actors/pull/278/files#diff-8772ad0ee72bb85e1ee2b17104a7f65a7c5bbb2b5da5712b50528b2695fe24a9R11-R13, right? 

Let's have a follow-up PR that introduces this change (or even include it in this PR, I don't think it'll be a big change)

_Originally posted by @adlrocha in https://github.com/consensus-shipyard/ipc-solidity-actors/pull/279#pullrequestreview-1740209062_

**Comment by adlrocha** [comment]
Hey, @snissn. What I was referring to here is that when there is an update to the reference implementation of the subnet actor, we need to also update the subnet actor code deployed in the registry. 

Currently the registry behaves as a factory for the subnet diamond and it [points to the subnet diamond facets and selectors](https://github.com/consensus-shipyard/ipc-solidity-actors/blob/3085747b830c99888b7d0d803048da1743310978/src/SubnetRegistryDiamond.sol#L46-L50) that it needs to deploy new instances. If we release a new version of the subnet diamond, we will need to also update these values. For this, we probably don't need to upgrade the registry, and it is enough to have an additional method in the `SubnetGetterFacet` to `updateReferenceSubnetContract`, where we as owners can update the reference implementation of the subnet actor deployed by the registry. 

Let me know if this is clear (we can probably sync at some point if it's still not clear, it may be more efficient :) )

**Comment by snissn** [comment]
thank you for explaining! Per the sync chat we just had I will create a setter method for the variables
```
        // address getterFacet;
        // address managerFacet;
        // bytes4[] subnetGetterSelectors;
        // bytes4[] subnetManagerSelectors;
```
