### ISSUE TITLE
SubnetRegistry does not follow the Diamond pattern

### ISSUE THREAD

**Issue by dnkolegov** [consensus-shipyard/ipc-solidity-actors#301]
In https://github.com/consensus-shipyard/ipc-solidity-actors/blob/ced08f5acc5b953ec5c2a604bf88a04bf6b72036/src/lib/LibSubnetRegistryStorage.sol#L9-L15

`SubnetRegistry` stores all Diamond-specific data. At the same time, those data are stored in `LibDiamond`, which is used in all facets.
There is no need to store selectors and facet addresses in the facet until there are strong reasons for that.

**Comment by snissn** [comment]
Hi @dnkolegov,

Thank you for bringing this to attention. To clarify the implementation in `SubnetRegistry`, it indeed follows a structure similar to what we have in `GatewayDiamond`. The `SubnetRegistry` imports and utilizes the `SubnetRegistryActorStorage` struct from `LibSubnetRegistryStorage.sol`, analogous to how `GatewayDiamond` uses its respective storage struct:

```solidity
// In SubnetRegistryDiamond.sol
import {SubnetRegistryActorStorage} from "./lib/LibSubnetRegistryStorage.sol";

contract SubnetRegistryDiamond {
    SubnetRegistryActorStorage internal s;
    // ConstructorParams and other details...
}
```

This pattern is mirrored in the `GatewayDiamond`:

```solidity
// In GatewayDiamond.sol
import {GatewayActorStorage} from "./lib/LibGatewayStorage.sol";

contract GatewayDiamond {
    GatewayActorStorage internal s;
    // ConstructorParams and other details...
}
```

The struct usage across both `GatewayDiamond` and `SubnetRegistryDiamond` indicates a consistent application of the Diamond pattern in our architecture. The storage struct being imported and used in facets aligns with the Diamond standard and ensures that we maintain a modular, upgradeable, and efficient contract structure.

Could you please review this explanation and let me know if it addresses your concerns regarding the Diamond pattern implementation in `SubnetRegistry`? If there are specific aspects or reasons you believe it doesn't align with the pattern, or if there are any other concerns, I'm open to discussing them further to ensure we're on the same page.

**Comment by dnkolegov** [comment]
I meant that it does not follow Diamond because only `SubnetRegistryActorStorage` stores facet addresses and selectors in the storage.
What are the reasons for that? 
Traditionally, data like those are used in introspection facets like Loupe, etc.

**Comment by dnkolegov** [comment]
Agree
