### ISSUE TITLE
unused validation code in crossMsgHelper

### ISSUE THREAD

**Issue by snissn** [consensus-shipyard/ipc-solidity-actors#361]
https://github.com/consensus-shipyard/ipc-solidity-actors/blob/9c85f9d110ba10737d258094085e70bb9f0ad54d/src/lib/CrossMsgHelper.sol#L72C59-L72C59

`isEmpty` appears to be unused

**Comment by dnkolegov** [comment]
It is used in the tests - test/unit/CrossMsgHelper.t.sol:28
I would keep it until the protocol and codebase is stable

**Comment by snissn** [comment]
> It is used in the tests - test/unit/CrossMsgHelper.t.sol:28 I would keep it until the protocol and codebase is stable

sounds good to me!

**Comment by snissn** [comment]
if we come back to this here's the related PR https://github.com/consensus-shipyard/ipc-solidity-actors/pull/362
